kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: javaneiros
spec:
  type: NodePort
  # type: LoadBalancer
  # loadBalancerIP: 192.168.99.100
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http

