kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: javaneiros
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http


