kind: Service
apiVersion: v1
metadata:
  name: tomcat
  namespace: javaneiros
spec:
  type: NodePort
  selector:
    app: tomcat
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http