kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: tomcat
  namespace: javaneiros
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: anspfeifer/tomcat8:2.0
        resources:
          limits:
            cpu: 0.4
            memory: 512Mi
          requests:
            cpu: 0.3
            memory: 256Mi
        ports:
        - containerPort: 8080
        env:
        - name: JAVA_OPTS
          value: "-Xmx256M"
